# .github/workflows/scrape.yml

name: Run Octopart Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- MODIFIED WORKFLOW ---
      # Step 3: Install system dependencies including Chrome AND the virtual display
      - name: Install Google Chrome and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      # Step 4: Install Python dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Step 5: Run the scraper using the virtual display
      # The "xvfb-run" command automatically starts a virtual screen and runs
      # our python script inside it.
      - name: Run the Octopart scraper with a virtual display
        run: xvfb-run --auto-servernum python get_octopart_products.py

      # Step 6: Upload the results as an artifact
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: octopart-product-urls
          path: octopart_product_urls.txt
